### ISSUE TITLE
[FEATURE] Ability to use address literal as valid HELO command argument

### ISSUE THREAD

**Issue by dandare100** [mocktools/go-smtp-mock#112]
### New feature checklist

- [x] I have updated `smtpmock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### Feature description

Ability to use address literal as valid HELO command argument, for example: `ehlo [192.168.1.1]`. Current version of `go-smtp-mock` for this request responds with:

```bash
220 Welcome
ehlo [192.168.1.1]
501 HELO requires domain address  
```

According to  [https://datatracker.ietf.org/doc/html/rfc2821#section-4.1.1.1](url) the mail client SHOULD send an address literal if the client system does not have a meaningful domain name.

**Comment by bestwebua** [comment]
Hello, @dandare100! Agree, but seems like `[192.168.1.1]` is a correct address literal: https://www.iana.org/assignments/address-literal-tags/address-literal-tags.xhtml

But I have never seen that this example has been accepted by real smtp servers... Maybe it will be good point to accept the both cases `echo 1.2.3.4` and `ehlo [1.2.3.4]` for more flexibility?

**Comment by bestwebua** [comment]
Hellyeah, @dandare100! Seems like we need to add ability to use next args as valid `HELO` command args:

1. `[1.2.3.4]`
2. `1.2.3.4`
3. `localhost`

I have tested your flow, and yes. The same behaviour during my mikrotik router iteraction with `smtpmock`:

<img width="1576" alt="Screenshot 2022-09-08 at 15 07 10" src="https://user-images.githubusercontent.com/14002692/189129840-48b2d20c-c8fa-46a6-aeb6-a9256b7d46e4.png">

**Comment by dandare100** [comment]
@bestwebua Agreed, it is a feature.

I have updated the PR, can you squash the commits on your side or do you want me to create a new one with a single commit ?

**Comment by bestwebua** [comment]
> I have updated the PR, can you squash the commits on your side or do you want me to create a new one with a single commit ?

Yup, @dandare100 . It's better if you you close current PR and reopen new one, guided by our [branch naming convention](https://github.com/mocktools/go-smtp-mock/blob/master/.github/BRANCH_NAMING_CONVENTION.md). You target branch name should be: `feature/ability-to-use-address-literal-as-valid-helo-command-argument`.

> Also, thanks for the Mikrotik confirmation. I see I need to upgrade my firmware...lol

Good point 👍

**Comment by dandare100** [comment]
Done

**Comment by bestwebua** [comment]
Already in a new release 🚀: https://github.com/mocktools/go-smtp-mock/releases/tag/v1.10.0
Thank you, @dandare100
