### ISSUE TITLE
[BUG] BrokenImport, could not import (no required module provides package)

### ISSUE THREAD

**Issue by TechDufus** [mocktools/go-smtp-mock#137]
### New bug checklist

- [x] I have updated `smtpmock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### Bug description

When following the instructions on installing / importing in Go, I'm running into the following issue...

1. Install smtpmock:
```bash
go get github.com/mocktools/go-smtp-mock/v2
go install github.com/mocktools/go-smtp-mock/v2/smtpmock@latest
```
 
    Output: go: github.com/mocktools/go-smtp-mock/v2/smtpmock@latest: module github.com/mocktools/go-smtp-mock/v2@latest found (v2.0.1), but does not contain package github.com/mocktools/go-smtp-mock/v2/smtpmock

2. Import statement error in go package:
```error
compiler: could not import github.com/mocktools/go-smtp-mock/v2 (no required module provides package "github.com/mocktools/go-smtp-mock/v2") [BrokenImport]
```

Am I doing something obviously wrong?

I'm using `go version go1.19.3 linux/amd64`

**Comment by bestwebua** [comment]
Him @TechDufus! Thanks. Seems like we need to update docs 👍. Could you try these commands?:

```bash
go clean -modcache

go get github.com/mocktools/go-smtp-mock/v2
# => go: downloading github.com/mocktools/go-smtp-mock/v2 v2.0.1
# => go: downloading github.com/mocktools/go-smtp-mock v1.10.0

go install github.com/mocktools/go-smtp-mock/v2
```

**Comment by TechDufus** [comment]
This did the trick... THANK YOU... Now I'm off to break this mock implementation.... ;)

**Comment by bestwebua** [comment]
Good luck 😃
