### ISSUE TITLE
[BUG] Data race between `newMessage()` and `Messages()`

### ISSUE THREAD

**Issue by achivkun** [mocktools/go-smtp-mock#150]
### New bug checklist

- [x] I have updated `smtpmock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### Bug description
`Messages()` call protected with:
```
	server.Lock()
	defer server.Unlock()
```
but `newMessage()` doesn't. It looks like because of this we can have following race condition:
```
WARNING: DATA RACE
Read at 0x00c00024a950 by goroutine 9:
  github.com/mocktools/go-smtp-mock/v2.(*Server).Messages()
      /home/anton/go/pkg/mod/github.com/mocktools/go-smtp-mock/v2@v2.0.4/server.go:128 +0x1ab
...
Previous write at 0x00c00024a950 by goroutine 25:
  github.com/mocktools/go-smtp-mock/v2.(*messages).append()
      /home/anton/go/pkg/mod/github.com/mocktools/go-smtp-mock/v2@v2.0.4/message.go:154 +0x11b
  github.com/mocktools/go-smtp-mock/v2.(*Server).newMessage()
      /home/anton/go/pkg/mod/github.com/mocktools/go-smtp-mock/v2@v2.0.4/server.go:181 +0xfd
...
```

Please kindly let me know if direction of my thoughts is right, or there is some other reason for this race?
Thanks in advance!

##### Complete output when running smtpmock, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by bestwebua** [comment]
@achivkun Could you provide some code examples to get this race condition? I think everything is fine with `Server#newServer`. What do you think, @benjamin-rood?

**Comment by achivkun** [comment]
@bestwebua, @benjamin-rood, here is example of test, which will fail with `-race` option:

```
package app_test

import (
	"fmt"
	"net/smtp"
	"testing"
	"time"

	smtpmock "github.com/mocktools/go-smtp-mock/v2"
	"github.com/stretchr/testify/assert"
)

func TestServer(t *testing.T) {
	hostName := "localhost"
	server := smtpmock.New(smtpmock.ConfigurationAttr{
		LogToStdout:       true,
		LogServerActivity: true,
		HostAddress:       hostName,
	})

	if err := server.Start(); err != nil {
		fmt.Println(err)
	}

	go smtp.SendMail(
		fmt.Sprintf("%s:%d", hostName, server.PortNumber()),
		smtp.PlainAuth("id", "user", "password", hostName),
		"test@test.com",
		[]string{"dest@dest.com"},
		[]byte("some msg"),
	)

	time.Sleep(1 * time.Second)
	assert.Equal(t, true, len(server.Messages()) == 1, server.Messages())

	if err := server.Stop(); err != nil {
		fmt.Println(err)
	}
}
```

**Comment by benjamin-rood** [comment]
Hi guys, I'm on holiday with my young family on the other side of the world
until Feb 1st, so I have no way of debugging this or writing the code to
change anything, sorry, but I can provide my best guess at the solution.

I have run into something like this myself with concurrent access to a
single server instance. I think there is a mistake (by me) in the
`server.Messages` implementation.

https://github.com/mocktools/go-smtp-mock/blob/87efa37169545d7887bf6f2d8a12cbaae5e0bf41/server.go#L126

```
func (server *Server) Messages() []Message {
  server.Lock()
  defer server.Unlock()
  copiedMessages, messages := []Message{}, server.messages.items
  for index := range messages {
  copiedMessages = append(copiedMessages, *messages[index])
}

  return copiedMessages
}
```

I think we should try adding a call to the Mutex on `server.messages` -
i.e. instead of locking the server, we should be locking `server.messages`.

**Comment by bestwebua** [comment]
@benjamin-rood Hello, Benjamin! Thanks for the super quick response. Have a perfect vacation for you and your family! I think that this issue can wait a bit. If I won't figure it out I'll ask your help after your vacation :)


P.S.: I have tried change locks from `Server` to `messages` - the same result with race condition...

```go
func (server *Server) Messages() []Message {
	server.messages.Lock()         // locking messages instead Server
	defer server.messages.Unlock() // unlocking messages instead Server
	copiedMessages, messages := []Message{}, server.messages.items
	for index := range messages {
		copiedMessages = append(copiedMessages, *messages[index])
	}

	return copiedMessages
}
```

**Comment by benjamin-rood** [comment]
Okay. Then we need to go deeper: we either need to implement a read/write
blocking QUEUE for all calls which interact with the messages (with an
unbuffered channel), or change from using a slice of messages to a
concurrent-safe data structure, like sync/map and treat it like a
sequential list (where the map indexes are 0, 1, 2, ..., n).

**Comment by benjamin-rood** [comment]
Let me explain why the above is necessary: the messages array is
effectively a simple in-memory database, and we are asking it to have the
same (or similar) API to a proper database with the appropriate concurrency
guarantees. As we know, in reality a database is not just blobs of data
organised in a structured manner, it is also the means by which that data
may be accessed or manipulated safely via read or write transactions that
are queued to preserve data integrity.

The change I am proposing is not a breaking one, because the API will not
change. The `Messages()` method would still return a slice of all message
data, sending a new messages to the server would still work exactly the
same way, etc. Only the underlying implementation with respect to message
storage changes. The good news is that this is quite a fun thing to
implement!

**Comment by bestwebua** [comment]
@benjamin-rood Agree! I'm researching this topic right now ❤️

**Comment by benjamin-rood** [comment]
@bestwebua Sorry, been slammed with work and life since I got back from holiday. I want to get stuck into fixing this if you haven't already done so?

**Comment by bestwebua** [comment]
@benjamin-rood Hi, Benjamin! It's sad, I also had a lot of work to do. Haven't actually done it yet and would appreciate your input!

**Comment by mitar** [comment]
Please fix this.

**Comment by mitar** [comment]
I made https://github.com/mocktools/go-smtp-mock/pull/173 to fix this.

> Then we need to go deeper: we either need to implement a read/write blocking QUEUE for all calls which interact with the messages (with an unbuffered channel),

We do not need to do an explicit blocking queue. Having a mutex creates an implicit queue on the data structure. Simply all data reads and writes to a shared data structure (in this case messages slices) has to be protected by a mutex.

**Comment by bestwebua** [comment]
@mitar Does this update fix data race condition described above?

**Comment by mitar** [comment]
Yes!

**Comment by mitar** [comment]
> Does this update fix data race condition described above?

Yes.

> Does it appear on the same test env with same run conditions without your fix?

A very similar test (effectively the same). But I can also test the exact one if you want.

**Comment by bestwebua** [comment]
@mitar If you have a time check it with exact one, please!

**Comment by mitar** [comment]
OK. Let me test that out.

**Comment by mitar** [comment]
OK, I added the test above to tests in the repository. That was a good call because I had to rework the fix. I updated PR accordingly.

**Comment by bestwebua** [comment]
In latest release! Thanks @mitar for your involvement!
