### ISSUE TITLE
[BUG] Cannot use localhost as domain in MAIL FROM

### ISSUE THREAD

**Issue by Deracination** [mocktools/go-smtp-mock#156]
Using v2.0.5 doesn't accept localhost as valid for MAIL FROM addresses

Expected result (using postfix):
```
220 gokyo.local ESMTP Postfix
HELO localhost
250 gokyo.local
MAIL FROM: <dev@localhost>
250 2.1.0 Ok
```

Result with smtpmock 2.0.5:
```
220 Welcome
HELO localhost
250 Received
MAIL FROM: <dev@localhost>
501 MAIL FROM requires valid email address
```

**Comment by bestwebua** [comment]
@Deracination, already in latest release: https://github.com/mocktools/go-smtp-mock/releases/tag/v2.2.0
