### ISSUE TITLE
[FEATURE] Ability to use localhost as valid HELO domain

### ISSUE THREAD

**Issue by lesichkovm** [mocktools/go-smtp-mock#54]
Getting this strange error when trying to send email to the server

INFO: 2021/12/13 00:39:13.629342 SMTP mock server started on port: 2525
INFO: 2021/12/13 00:39:23.666279 SMTP session started
INFO: 2021/12/13 00:39:23.666279 SMTP response: 220 Welcome
INFO: 2021/12/13 00:39:23.667275 SMTP request: EHLO localhost       
INFO: 2021/12/13 00:39:23.668414 SMTP response: 501 HELO requires domain address
INFO: 2021/12/13 00:39:23.669274 SMTP request: HELO localhost       
INFO: 2021/12/13 00:39:23.670276 SMTP response: 501 HELO requires domain address
2021/12/13 00:39:23 501 HELO requires domain address

Code to start the server:

```
server := smtpmock.New(smtpmock.ConfigurationAttr{
		LogToStdout:       true,
		LogServerActivity: true,
		PortNumber:        2525,
		HostAddress:       "127.0.0.1",
	})

	// To start server use Start() method
	if err := server.Start(); err != nil {
		fmt.Println(err)
	}
```

**Comment by bestwebua** [comment]
Hi, @lesichkovm! Thanks for your report. It's okay. It causes because `localhost` isn't valid domain name. Today I'll add feature to able using `localhost` as valid HELO domain. Often, email providers reject requests containing `localhost` as HELO domain recognizing them as suspicious.

**Comment by bestwebua** [comment]
@lesichkovm, you able to use `localhost` as `HELO` argument using latest `smtpmock` [release](https://github.com/mocktools/go-smtp-mock/releases/tag/v1.2.0). Cheers!

**Comment by lesichkovm** [comment]
Great job guys. Works as a charm 👍
