### ISSUE TITLE
[BUG] Wrong order of `hostAddress` and `portNumber` variables values

### ISSUE THREAD

**Issue by vpakhuchyi** [mocktools/go-smtp-mock#57]
### New bug checklist

- [x] I have updated `go-smtp-mock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### Bug description
`hostAddress` and `portNumber` variables values are mixed up:
``` 
hostAddress, portNumber =: server.PortNumber, "127.0.0.1"
```

**Comment by bestwebua** [comment]
@vpakhuchyi Thanks, man! 🍺 I have merged it in develop.
