### ISSUE TITLE
[BUG] Fixing typos and shorthand declaration in README

### ISSUE THREAD

**Issue by srishti-nema** [mocktools/go-smtp-mock#73]
### New bug checklist

- [x] I have updated `smtpmock` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### Bug description

Incorrect shorthand declaration operator in the code present in README.md file in the following line:

`  hostAddress, portNumber =: "127.0.0.1", server.PortNumber
`

Fixed spelling for two other words as well.

**Comment by bestwebua** [comment]
Thank you so much, @srishti-nema ;)
