### ISSUE TITLE
[QUESTION] How to check Mail server messages content, or How to read Server logs inside tests?

### ISSUE THREAD

**Issue by vzool** [mocktools/go-smtp-mock#94]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/mocktools/go-smtp-mock/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/mocktools/go-smtp-mock/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/mocktools/go-smtp-mock/issues)

### How to check Mail server messages content, or How to read Server logs inside tests?

**Comment by vzool** [comment]
Is there any APIs like this:
```golang
output := captureOutput(func() {
    client.RemoveCertificate("www.example.com")
})
assert.Equal(t, "removed certificate www.example.com\n", output)
```
Source
```golang
func captureOutput(f func()) string {
	var buf bytes.Buffer
	log.SetOutput(&buf)
	f()
	log.SetOutput(os.Stderr)
	return buf.String()
}
```
[REF](https://stackoverflow.com/questions/26804642/how-to-test-a-functions-output-stdout-stderr-in-unit-tests)

**Comment by bestwebua** [comment]
Hello, @vzool! Thanks for your request & PR. This feature already in new release.
